"""Pure, content-addressed exports for exact Verifiers compatibility profiles.

Prime RL v0.7.0 does not use standalone Verifiers v0.2.1. Its ``uv`` workspace
redirects Verifiers to the editable ``deps/verifiers`` gitlink at commit
``6c64ce6...``, which is release v0.2.0. This adapter models those two upstream
states separately and refuses to describe them as interchangeable.

Building a bundle performs no Verifiers import, installation, network request,
upload, or execution. Materialization is an explicit, exact-file handoff whose
generated loader verifies its task data before constructing any task objects.
"""
from __future__ import annotations

import hashlib
import json
import math
import re
from dataclasses import dataclass
from enum import Enum
from pathlib import Path, PurePosixPath

from .backends import (
    PRIME_RL_VERIFIERS_SUBMODULE_COMMIT,
    PRIME_RL_VERIFIERS_TAG,
    PRIME_RL_VERIFIERS_VERSION,
    TrainingBackendError,
    admit_training_boundary,
    canonical_training_tenant_id,
    normalize_training_target,
    training_admission_digest,
)
from .environments import (
    CASE_SCHEMA,
    BoundaryDecision,
    EnvironmentError,
    EnvironmentPack,
    export_rows,
    require_training_readiness,
)

VERIFIERS_EXPORT_SCHEMA = "lightwork.verifiers-export-bundle.v2"
VERIFIERS_RUNTIME_LOCK_SCHEMA = "lightwork.verifiers-runtime-lock.v2"
PORTABLE_SCORER_CONTRACT = "lightwork.deterministic-environment-reward.v1"
VERIFIERS_REPOSITORY = "https://github.com/PrimeIntellect-ai/verifiers"

# Prime RL v0.7.0's editable workspace source. These compatibility aliases are
# intentionally the default because Prime is the only trainer emitted here.
VERIFIERS_VERSION = PRIME_RL_VERIFIERS_VERSION
VERIFIERS_TAG = PRIME_RL_VERIFIERS_TAG
VERIFIERS_COMMIT = PRIME_RL_VERIFIERS_SUBMODULE_COMMIT
VERIFIERS_SOURCE = f"{VERIFIERS_REPOSITORY}/tree/{VERIFIERS_COMMIT}"

# The later standalone release is supported only as an explicit export profile.
STANDALONE_VERIFIERS_VERSION = "0.2.1"
STANDALONE_VERIFIERS_TAG = "v0.2.1"
STANDALONE_VERIFIERS_COMMIT = "ab65b6e8d34b03d162408d4bcb854430a86809e6"
STANDALONE_VERIFIERS_SOURCE = (
    f"{VERIFIERS_REPOSITORY}/tree/{STANDALONE_VERIFIERS_COMMIT}"
)

_SAFE_SLUG_RE = re.compile(r"[^a-z0-9]+")


class VerifiersCompatibility(str, Enum):
    """Reviewed upstream states; commit equality is part of compatibility."""

    PRIME_RL_V070 = "prime-rl-v0.7.0"
    STANDALONE_V021 = "standalone-v0.2.1"


class BundlePurpose(str, Enum):
    """Keep trainer data and evaluation-only data structurally distinct."""

    TRAINING = "training"
    EVALUATION = "evaluation"


@dataclass(frozen=True, slots=True)
class _VerifiersPin:
    profile: VerifiersCompatibility
    version: str
    tag: str
    commit: str

    def public_dict(self) -> dict[str, str]:
        return {
            "name": "verifiers",
            "repository": VERIFIERS_REPOSITORY,
            "profile": self.profile.value,
            "tag": self.tag,
            "version": self.version,
            "commit": self.commit,
        }


_PINS = {
    VerifiersCompatibility.PRIME_RL_V070: _VerifiersPin(
        profile=VerifiersCompatibility.PRIME_RL_V070,
        version=VERIFIERS_VERSION,
        tag=VERIFIERS_TAG,
        commit=VERIFIERS_COMMIT,
    ),
    VerifiersCompatibility.STANDALONE_V021: _VerifiersPin(
        profile=VerifiersCompatibility.STANDALONE_V021,
        version=STANDALONE_VERIFIERS_VERSION,
        tag=STANDALONE_VERIFIERS_TAG,
        commit=STANDALONE_VERIFIERS_COMMIT,
    ),
}

_PORTABLE_SCORER_SOURCE = '''"""Self-contained deterministic Lightwork reward contract.

This file is generated by Lightwork, committed by ``bundle.lock.json``, and
verified byte-for-byte by ``taskset.py`` before it is executed.  It intentionally
uses only the Python standard library: training rewards cannot drift with an
ambient ``maverick-agent`` installation.
"""
from __future__ import annotations

import json
import math
from collections.abc import Mapping

SCORER_CONTRACT = "lightwork.deterministic-environment-reward.v1"
MAX_OUTPUT_BYTES = 128 * 1024
_CASE_FIELDS = {
    "case_id",
    "environment_id",
    "split",
    "family_id",
    "expected",
    "required_citations",
    "required_reason_codes",
    "source_id",
    "evidence_text",
    "unordered_fields",
}


class ScorerError(ValueError):
    """The locked task payload is not a valid scorer input."""


def _canonical(value: object) -> bytes:
    return json.dumps(
        value,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
    ).encode("utf-8")


def _strict_json_loads(value: str) -> object:
    def reject_constant(token: str) -> object:
        raise ScorerError(f"non-standard JSON constant {token!r}")

    def reject_duplicate_keys(pairs: list[tuple[str, object]]) -> dict[str, object]:
        out: dict[str, object] = {}
        for key, item in pairs:
            if key in out:
                raise ScorerError(f"duplicate JSON field {key!r}")
            out[key] = item
        return out

    try:
        return json.loads(
            value,
            parse_constant=reject_constant,
            object_pairs_hook=reject_duplicate_keys,
        )
    except json.JSONDecodeError as exc:
        raise ScorerError("invalid JSON") from exc


def _strict_json_value(value: object, *, depth: int = 0) -> bool:
    if depth > 32:
        return False
    if value is None or isinstance(value, (str, bool, int)):
        return (
            not isinstance(value, int)
            or isinstance(value, bool)
            or abs(value) <= 10**100
        )
    if isinstance(value, float):
        return math.isfinite(value)
    if isinstance(value, list):
        return len(value) <= 10_000 and all(
            _strict_json_value(item, depth=depth + 1) for item in value
        )
    if isinstance(value, Mapping):
        return (
            len(value) <= 10_000
            and all(isinstance(key, str) for key in value)
            and all(
                _strict_json_value(item, depth=depth + 1)
                for item in value.values()
            )
        )
    return False


def _validated_case(case: object) -> dict[str, object]:
    if not isinstance(case, Mapping) or set(case) != _CASE_FIELDS:
        raise ScorerError("case payload has missing or unexpected fields")
    copied = dict(case)
    if (
        not isinstance(copied["case_id"], str)
        or not copied["case_id"]
        or not isinstance(copied["expected"], Mapping)
        or not _strict_json_value(copied["expected"])
        or not isinstance(copied["source_id"], str)
        or not isinstance(copied["evidence_text"], str)
    ):
        raise ScorerError("case payload has invalid deterministic scoring data")
    for field in (
        "required_citations",
        "required_reason_codes",
        "unordered_fields",
    ):
        value = copied[field]
        if (
            not isinstance(value, list)
            or len(value) > 64
            or not all(isinstance(item, str) and item for item in value)
        ):
            raise ScorerError(f"case payload {field} is invalid")
    return copied


def _leaf_pairs(
    value: object,
    prefix: str = "",
    *,
    unordered_fields: frozenset[str] = frozenset(),
) -> dict[str, object]:
    if isinstance(value, Mapping):
        out: dict[str, object] = {}
        for key, item in sorted(value.items(), key=lambda pair: str(pair[0])):
            label = f"{prefix}.{key}" if prefix else str(key)
            out.update(
                _leaf_pairs(
                    item,
                    label,
                    unordered_fields=unordered_fields,
                )
            )
        return out
    if isinstance(value, list):
        if prefix in unordered_fields:
            return {prefix: sorted(value, key=_canonical)}
        return {prefix: value}
    return {prefix: value}


def _score_citations(
    case: Mapping[str, object],
    citations: object,
) -> tuple[float, bool]:
    if not isinstance(citations, list) or len(citations) > 64:
        return 0.0, False
    grounded = True
    supplied_quotes: set[str] = set()
    seen_citations: set[bytes] = set()
    for citation in citations:
        if not isinstance(citation, Mapping) or set(citation) != {
            "source_id",
            "quote",
            "start",
            "end",
        }:
            grounded = False
            continue
        encoded = _canonical(dict(citation))
        if encoded in seen_citations:
            grounded = False
            continue
        seen_citations.add(encoded)
        source_id = citation.get("source_id")
        quote = citation.get("quote")
        start = citation.get("start")
        end = citation.get("end")
        evidence_text = case["evidence_text"]
        if (
            source_id != case["source_id"]
            or not isinstance(quote, str)
            or not quote
            or not isinstance(start, int)
            or isinstance(start, bool)
            or not isinstance(end, int)
            or isinstance(end, bool)
            or start < 0
            or end < start
            or end > len(evidence_text)
            or evidence_text[start:end] != quote
        ):
            grounded = False
            continue
        supplied_quotes.add(quote)
    required = case["required_citations"]
    score = (
        sum(1 for quote in required if quote in supplied_quotes) / len(required)
        if required
        else 1.0
    )
    return score, grounded


def _score_reason_codes(
    case: Mapping[str, object],
    reason_codes: object,
) -> tuple[float, bool]:
    if (
        not isinstance(reason_codes, list)
        or len(reason_codes) > 64
        or not all(isinstance(item, str) and item for item in reason_codes)
    ):
        return 0.0, False
    supplied = set(reason_codes)
    required = set(case["required_reason_codes"])
    if not required:
        score = 1.0 if not supplied else 0.0
    else:
        score = len(supplied & required) / len(required)
        if supplied - required:
            score = min(score, 0.5)
    exact = score == 1.0 and len(reason_codes) == len(supplied)
    return score, exact


def score_output(case: object, output: object) -> float:
    """Return the exact deterministic reward used by the locked taskset."""
    payload = _validated_case(case)
    if isinstance(output, str):
        if len(output.encode("utf-8")) > MAX_OUTPUT_BYTES:
            return 0.0
        try:
            candidate = _strict_json_loads(output)
        except ScorerError:
            return 0.0
    elif isinstance(output, Mapping):
        candidate = dict(output)
    else:
        return 0.0
    if not isinstance(candidate, dict) or not _strict_json_value(candidate):
        return 0.0
    try:
        if len(_canonical(candidate)) > MAX_OUTPUT_BYTES:
            return 0.0
    except (TypeError, ValueError):
        return 0.0

    expected = payload["expected"]
    allowed = set(expected) | {"citations", "reason_codes"}
    extra = set(candidate) - allowed
    unordered = frozenset(payload["unordered_fields"])
    expected_leaves = _leaf_pairs(expected, unordered_fields=unordered)
    candidate_leaves = _leaf_pairs(
        {
            key: value
            for key, value in candidate.items()
            if key not in {"citations", "reason_codes"}
        },
        unordered_fields=unordered,
    )
    matches = sum(
        1
        for path, value in expected_leaves.items()
        if path in candidate_leaves and candidate_leaves[path] == value
    )
    correctness = matches / len(expected_leaves) if expected_leaves else 1.0
    extra_leaf_paths = set(candidate_leaves) - set(expected_leaves)
    citation_score, _grounded = _score_citations(
        payload,
        candidate.get("citations", []),
    )
    reason_code_score, _reason_codes_exact = _score_reason_codes(
        payload,
        candidate.get("reason_codes", []),
    )
    reward = (
        0.80 * correctness
        + 0.15 * citation_score
        + 0.05 * reason_code_score
    )
    return reward if not extra and not extra_leaf_paths else min(reward, 0.5)
'''

_TASKSET_TEMPLATE = '''"""Generated deterministic Lightwork taskset for exact Verifiers."""
from __future__ import annotations

import hashlib
import json
import types
from importlib.metadata import version
from pathlib import Path
from typing import Any

import verifiers.v1 as vf

EXPECTED_VERIFIERS_VERSION = "__VERIFIERS_VERSION__"
EXPECTED_VERIFIERS_COMMIT = "__VERIFIERS_COMMIT__"
EXPECTED_RUNTIME_LOCK_SHA256 = "__RUNTIME_LOCK_SHA256__"
EXPECTED_SCORER_SHA256 = "__SCORER_SHA256__"
RUNTIME_LOCK_SCHEMA = "lightwork.verifiers-runtime-lock.v2"
SCORER_CONTRACT = "lightwork.deterministic-environment-reward.v1"

if version("verifiers") != EXPECTED_VERIFIERS_VERSION:
    raise RuntimeError(
        "Lightwork taskset requires the operator-provisioned "
        f"verifiers=={EXPECTED_VERIFIERS_VERSION}"
    )


def _canonical_bytes(value: object) -> bytes:
    return json.dumps(
        value,
        ensure_ascii=False,
        separators=(",", ":"),
        sort_keys=True,
    ).encode("utf-8")


def _load_verified_lock() -> tuple[Path, dict[str, Any]]:
    package_root = Path(__file__).parent
    lock_blob = (package_root / "bundle.lock.json").read_bytes()
    if hashlib.sha256(lock_blob).hexdigest() != EXPECTED_RUNTIME_LOCK_SHA256:
        raise RuntimeError("Lightwork runtime lock integrity verification failed")
    lock = json.loads(lock_blob)
    if (
        not isinstance(lock, dict)
        or lock.get("schema") != RUNTIME_LOCK_SCHEMA
        or lock.get("upstream", {}).get("version") != EXPECTED_VERIFIERS_VERSION
        or lock.get("upstream", {}).get("commit") != EXPECTED_VERIFIERS_COMMIT
    ):
        raise RuntimeError("Lightwork runtime lock is not compatible with this taskset")
    return package_root, lock


def _load_verified_scorer():
    package_root, lock = _load_verified_lock()
    commitment = lock.get("scorer")
    if (
        not isinstance(commitment, dict)
        or set(commitment) != {"path", "sha256", "bytes", "contract"}
        or commitment.get("path") != "scorer.py"
        or commitment.get("sha256") != EXPECTED_SCORER_SHA256
        or commitment.get("contract") != SCORER_CONTRACT
    ):
        raise RuntimeError("Lightwork scorer commitment is invalid")
    scorer_path = package_root / "scorer.py"
    scorer_blob = scorer_path.read_bytes()
    if (
        commitment.get("bytes") != len(scorer_blob)
        or hashlib.sha256(scorer_blob).hexdigest() != EXPECTED_SCORER_SHA256
    ):
        raise RuntimeError("Lightwork scorer integrity verification failed")
    module = types.ModuleType(f"{__package__}._verified_scorer")
    module.__file__ = str(scorer_path)
    exec(compile(scorer_blob, str(scorer_path), "exec"), module.__dict__)
    scorer = getattr(module, "score_output", None)
    if (
        getattr(module, "SCORER_CONTRACT", None) != SCORER_CONTRACT
        or not callable(scorer)
    ):
        raise RuntimeError("Lightwork scorer contract is invalid")
    return scorer


_SCORE_OUTPUT = _load_verified_scorer()


def _load_verified_rows() -> list[dict[str, Any]]:
    package_root, lock = _load_verified_lock()

    task_commitment = lock.get("tasks")
    if not isinstance(task_commitment, dict):
        raise RuntimeError("Lightwork runtime lock has no task commitment")
    tasks_blob = (package_root / "tasks.jsonl").read_bytes()
    if (
        task_commitment.get("bytes") != len(tasks_blob)
        or task_commitment.get("sha256")
        != hashlib.sha256(tasks_blob).hexdigest()
    ):
        raise RuntimeError("Lightwork task data integrity verification failed")

    lines = tasks_blob.splitlines()
    commitments = lock.get("case_commitments")
    if not isinstance(commitments, list) or len(commitments) != len(lines):
        raise RuntimeError("Lightwork task count does not match its commitment")
    rows: list[dict[str, Any]] = []
    for line, commitment in zip(lines, commitments):
        row = json.loads(line)
        if (
            not isinstance(row, dict)
            or set(row)
            != {
                "case_id",
                "case_digest",
                "environment_digest",
                "prompt",
                "case_payload",
            }
            or not isinstance(commitment, dict)
            or commitment.get("case_id") != row.get("case_id")
            or commitment.get("case_digest") != row.get("case_digest")
            or commitment.get("row_sha256")
            != hashlib.sha256(_canonical_bytes(row)).hexdigest()
        ):
            raise RuntimeError("Lightwork task row integrity verification failed")
        rows.append(row)
    return rows


class LightworkTaskData(vf.TaskData):
    """Trusted scoring data; only ``prompt`` is sent to the model."""

    case_payload: dict[str, Any]


class LightworkTask(vf.Task[LightworkTaskData]):
    @vf.stop
    async def single_turn(self, trace: vf.Trace) -> bool:
        return trace.num_turns >= 1

    @vf.reward(weight=1.0)
    async def deterministic_reward(self, trace: vf.Trace) -> float:
        return float(_SCORE_OUTPUT(
            self.data.case_payload,
            trace.last_reply or "",
        ))


class LightworkTaskset(vf.Taskset[LightworkTask, vf.TasksetConfig]):
    def load(self) -> list[LightworkTask]:
        return [
            LightworkTask(
                LightworkTaskData(
                    idx=index,
                    prompt=row["prompt"],
                    case_payload=row["case_payload"],
                ),
                self.config.task,
            )
            for index, row in enumerate(_load_verified_rows())
        ]
'''


class VerifiersExportError(RuntimeError):
    """A deterministic environment could not be exported safely."""


def _canonical_bytes(value: object) -> bytes:
    return json.dumps(
        value,
        ensure_ascii=False,
        separators=(",", ":"),
        sort_keys=True,
    ).encode("utf-8")


def _sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def _normalize_profile(
    value: VerifiersCompatibility | str,
) -> VerifiersCompatibility:
    try:
        return VerifiersCompatibility(value)
    except ValueError as exc:
        raise VerifiersExportError(
            f"unsupported Verifiers compatibility profile {value!r}",
        ) from exc


def _normalize_purpose(value: BundlePurpose | str) -> BundlePurpose:
    try:
        return BundlePurpose(value)
    except ValueError as exc:
        raise VerifiersExportError(f"unsupported bundle purpose {value!r}") from exc


def _package_names(
    environment_id: str,
    tenant_id: str,
    purpose: BundlePurpose,
    split: str,
    profile: VerifiersCompatibility,
) -> tuple[str, str]:
    slug = _SAFE_SLUG_RE.sub("-", environment_id.lower()).strip("-")
    if not slug:
        raise VerifiersExportError("environment_id cannot form a package name")
    tenant_digest = hashlib.sha256(tenant_id.encode("utf-8")).hexdigest()
    variant_digest = _sha256_bytes(_canonical_bytes({
        "environment_id": environment_id,
        "purpose": purpose.value,
        "split": split,
        "compatibility": profile.value,
    }))
    package_id = f"lw-t{tenant_digest[:16]}-b{variant_digest[:16]}"
    return package_id, package_id.replace("-", "_")


def _safe_relative_path(value: str) -> PurePosixPath:
    if not isinstance(value, str) or not value or "\\" in value or "\x00" in value:
        raise VerifiersExportError("bundle contains an unsafe relative path")
    path = PurePosixPath(value)
    if (
        path.is_absolute()
        or path.as_posix() != value
        or any(part in {"", ".", ".."} for part in path.parts)
    ):
        raise VerifiersExportError("bundle contains an unsafe relative path")
    return path


def _is_linklike(path: Path) -> bool:
    """Treat symlinks and Windows junctions as unsafe handoff indirection."""

    is_junction = getattr(path, "is_junction", None)
    return path.is_symlink() or bool(is_junction and is_junction())


@dataclass(frozen=True, slots=True)
class VerifiersBundleFile:
    """One immutable path/content pair in an export bundle."""

    path: str
    content: bytes

    @property
    def sha256(self) -> str:
        return _sha256_bytes(self.content)


@dataclass(frozen=True, slots=True)
class VerifiersExportBundle:
    """Deterministic Verifiers package, admission, and exact-file commitment."""

    package_id: str
    module_name: str
    tenant_id: str
    target: str
    hosted_boundary_permission: bool
    environment_id: str
    environment_version: str
    environment_digest: str
    purpose: str
    split: str
    compatibility: str
    verifiers_version: str
    verifiers_tag: str
    verifiers_revision: str
    case_ids: tuple[str, ...]
    files: tuple[VerifiersBundleFile, ...]
    digest: str
    boundary_decision_digest: str
    admission_digest: str
    manifest_sha256: str
    schema: str = VERIFIERS_EXPORT_SCHEMA

    def file_map(self) -> dict[str, bytes]:
        """Return a new mapping so callers cannot mutate the frozen bundle."""

        return {item.path: item.content for item in self.files}

    def manifest(self) -> dict[str, object]:
        """Read the canonical manifest shipped in this bundle."""

        value = json.loads(self.file_map()["manifest.json"])
        if not isinstance(value, dict):
            raise VerifiersExportError("bundle manifest is not an object")
        return value

    def boundary_decision(self) -> BoundaryDecision:
        """Return the exact authoritative decision committed by the manifest."""

        admission = self.manifest().get("admission")
        if not isinstance(admission, dict):
            raise VerifiersExportError("bundle manifest has no boundary admission")
        raw = admission.get("decision")
        if not isinstance(raw, dict):
            raise VerifiersExportError("bundle manifest has no boundary decision")
        admitted = raw.get("admitted_content_digests")
        reasons = raw.get("reasons")
        if not isinstance(admitted, dict) or not isinstance(reasons, list):
            raise VerifiersExportError("bundle boundary decision is malformed")
        decision = BoundaryDecision(
            allowed=raw.get("allowed"),
            target=raw.get("target"),
            reasons=tuple(reasons),
            pack_digest=raw.get("pack_digest"),
            registry_digest=raw.get("registry_digest"),
            admitted_content_digests=tuple(sorted(admitted.items())),
            evaluated_at=raw.get("evaluated_at"),
            schema=raw.get("schema"),
        )
        if decision.public_dict() != raw:
            raise VerifiersExportError("bundle boundary decision is not canonical")
        return decision

    def _upstream(self) -> dict[str, str]:
        return {
            "name": "verifiers",
            "repository": VERIFIERS_REPOSITORY,
            "profile": self.compatibility,
            "tag": self.verifiers_tag,
            "version": self.verifiers_version,
            "commit": self.verifiers_revision,
        }

    def _descriptor(
        self,
        file_commitments: dict[str, dict[str, object]],
    ) -> dict[str, object]:
        return {
            "schema": self.schema,
            "package_id": self.package_id,
            "module_name": self.module_name,
            "tenant_id": self.tenant_id,
            "purpose": self.purpose,
            "environment": {
                "id": self.environment_id,
                "version": self.environment_version,
                "digest": self.environment_digest,
                "split": self.split,
            },
            "boundary": {
                "target": self.target,
                "hosted_permission": self.hosted_boundary_permission,
                "cross_tenant": False,
            },
            "upstream": self._upstream(),
            "files": file_commitments,
        }

    def verify(self) -> bool:
        """Fail closed if any file, task row, pin, or admission binding changed."""

        try:
            if (
                self.schema != VERIFIERS_EXPORT_SCHEMA
                or canonical_training_tenant_id(self.tenant_id) != self.tenant_id
                or normalize_training_target(self.target).value != self.target
                or self.purpose not in {item.value for item in BundlePurpose}
                or (
                    self.purpose == BundlePurpose.TRAINING.value
                    and self.split != "train"
                )
                or (
                    self.purpose == BundlePurpose.EVALUATION.value
                    and self.split not in {"validation", "holdout"}
                )
                or tuple(sorted(self.files, key=lambda item: item.path)) != self.files
                or len({item.path for item in self.files}) != len(self.files)
            ):
                return False
            profile = _normalize_profile(self.compatibility)
            pin = _PINS[profile]
            if (
                self.verifiers_version != pin.version
                or self.verifiers_tag != pin.tag
                or self.verifiers_revision != pin.commit
            ):
                return False

            files = self.file_map()
            for path in files:
                _safe_relative_path(path)
            scorer_source = _portable_scorer_source()
            scorer_sha256 = _sha256_bytes(scorer_source)
            scorer_path = f"src/{self.module_name}/scorer.py"
            runtime_lock_path = f"src/{self.module_name}/bundle.lock.json"
            taskset_path = f"src/{self.module_name}/taskset.py"
            if files.get(scorer_path) != scorer_source:
                return False
            runtime_lock_blob = files[runtime_lock_path]
            runtime_lock = json.loads(runtime_lock_blob)
            expected_scorer_commitment = {
                "path": "scorer.py",
                "sha256": scorer_sha256,
                "bytes": len(scorer_source),
                "contract": PORTABLE_SCORER_CONTRACT,
            }
            if (
                not isinstance(runtime_lock, dict)
                or set(runtime_lock)
                != {
                    "schema",
                    "package_id",
                    "tenant_id",
                    "purpose",
                    "environment",
                    "upstream",
                    "tasks",
                    "scorer",
                    "case_commitments",
                }
                or runtime_lock.get("schema") != VERIFIERS_RUNTIME_LOCK_SCHEMA
                or runtime_lock.get("package_id") != self.package_id
                or runtime_lock.get("tenant_id") != self.tenant_id
                or runtime_lock.get("purpose") != self.purpose
                or runtime_lock.get("upstream") != self._upstream()
                or runtime_lock.get("scorer") != expected_scorer_commitment
                or files.get(taskset_path)
                != _taskset_source(pin, runtime_lock_blob, scorer_source)
            ):
                return False
            manifest_blob = files["manifest.json"]
            if _sha256_bytes(manifest_blob) != self.manifest_sha256:
                return False
            manifest = json.loads(manifest_blob)
            if not isinstance(manifest, dict):
                return False
            file_commitments = {
                item.path: {"sha256": item.sha256, "bytes": len(item.content)}
                for item in self.files
                if item.path != "manifest.json"
            }
            descriptor = self._descriptor(file_commitments)
            expected_controls = {
                "execution_performed": False,
                "auto_install": False,
                "network_required": False,
                "upload_enabled": False,
                "telemetry_enabled": False,
                "model_visible_fields": ["prompt"],
                "ambient_lightwork_dependency": False,
                "trusted_scoring_function": (
                    f"{self.module_name}.scorer.score_output"
                ),
                "trusted_scoring_source_sha256": scorer_sha256,
                "runtime_scorer_integrity_check": True,
                "runtime_task_integrity_check": True,
            }
            if (
                set(manifest)
                != {
                    "schema",
                    "bundle_digest",
                    "descriptor",
                    "package_id",
                    "module_name",
                    "tenant_id",
                    "environment",
                    "boundary",
                    "admission",
                    "upstream",
                    "controls",
                    "files",
                }
                or _sha256_bytes(_canonical_bytes(descriptor)) != self.digest
                or manifest.get("bundle_digest") != self.digest
                or manifest.get("descriptor") != descriptor
                or manifest.get("upstream") != self._upstream()
                or manifest.get("schema") != self.schema
                or manifest.get("package_id") != self.package_id
                or manifest.get("module_name") != self.module_name
                or manifest.get("tenant_id") != self.tenant_id
                or manifest.get("boundary") != descriptor["boundary"]
                or manifest.get("files") != file_commitments
                or manifest.get("controls") != expected_controls
            ):
                return False

            environment = manifest.get("environment")
            if not isinstance(environment, dict):
                return False
            commitments = environment.get("case_commitments")
            if (
                set(environment)
                != {
                    "id",
                    "version",
                    "digest",
                    "case_schema",
                    "purpose",
                    "split",
                    "case_commitments",
                }
                or environment.get("case_schema") != CASE_SCHEMA
                or environment.get("id") != self.environment_id
                or environment.get("version") != self.environment_version
                or environment.get("digest") != self.environment_digest
                or environment.get("split") != self.split
                or environment.get("purpose") != self.purpose
                or not isinstance(commitments, list)
                or tuple(item.get("case_id") for item in commitments) != self.case_ids
                or any(
                    not isinstance(item, dict)
                    or set(item)
                    != {
                        "case_id",
                        "case_digest",
                        "prompt_sha256",
                        "row_sha256",
                    }
                    for item in commitments
                )
            ):
                return False

            admission = manifest.get("admission")
            if (
                not isinstance(admission, dict)
                or set(admission) != {"digest", "decision_digest", "decision"}
            ):
                return False
            decision = self.boundary_decision()
            if (
                decision.allowed is not True
                or decision.target != self.target
                or decision.reasons
                or decision.pack_digest != self.environment_digest
                or not isinstance(decision.evaluated_at, (int, float))
                or isinstance(decision.evaluated_at, bool)
                or not math.isfinite(float(decision.evaluated_at))
                or decision.evaluated_at < 0
                or decision.digest != self.boundary_decision_digest
                or admission.get("decision_digest") != decision.digest
            ):
                return False
            expected_admission = training_admission_digest(
                decision,
                tenant_id=self.tenant_id,
                bundle_digest=self.digest,
            )
            if (
                admission.get("digest") != expected_admission
                or self.admission_digest != expected_admission
            ):
                return False

            task_path = f"src/{self.module_name}/tasks.jsonl"
            task_blob = files[task_path]
            if runtime_lock.get("tasks") != {
                "path": "tasks.jsonl",
                "sha256": _sha256_bytes(task_blob),
                "bytes": len(task_blob),
            }:
                return False
            rows = [
                json.loads(line)
                for line in task_blob.splitlines()
                if line
            ]
            if (
                runtime_lock.get("environment")
                != {
                    "id": self.environment_id,
                    "version": self.environment_version,
                    "digest": self.environment_digest,
                    "split": self.split,
                }
                or runtime_lock.get("case_commitments") != commitments
                or len(rows) != len(commitments)
            ):
                return False
            for row, commitment in zip(rows, commitments, strict=True):
                if (
                    not isinstance(row, dict)
                    or set(row)
                    != {
                        "case_id",
                        "case_digest",
                        "environment_digest",
                        "prompt",
                        "case_payload",
                    }
                    or row.get("case_id") != commitment.get("case_id")
                    or row.get("case_digest") != commitment.get("case_digest")
                    or row.get("environment_digest") != self.environment_digest
                    or not isinstance(row.get("prompt"), str)
                    or _sha256_bytes(row["prompt"].encode("utf-8"))
                    != commitment.get("prompt_sha256")
                    or _sha256_bytes(_canonical_bytes(row))
                    != commitment.get("row_sha256")
                ):
                    return False
            return True
        except (
            AttributeError,
            KeyError,
            OSError,
            TrainingBackendError,
            TypeError,
            ValueError,
            VerifiersExportError,
        ):
            return False

    def verify_against(self, pack: EnvironmentPack) -> bool:
        """Verify that every task row is the exact selected case from ``pack``."""

        try:
            if (
                not self.verify()
                or pack.environment_id != self.environment_id
                or pack.version != self.environment_version
                or pack.digest != self.environment_digest
                or self.boundary_decision().admitted_content_digests
                != tuple(sorted(
                    (case.case_id, case.admitted_content_sha256)
                    for case in pack.cases
                ))
            ):
                return False
            selected = tuple(sorted(
                pack.split(self.split),
                key=lambda case: case.case_id,
            ))
            if tuple(case.case_id for case in selected) != self.case_ids:
                return False
            task_path = f"src/{self.module_name}/tasks.jsonl"
            rows = [
                json.loads(line)
                for line in self.file_map()[task_path].splitlines()
                if line
            ]
            if len(rows) != len(selected):
                return False
            return all(
                row == {
                    "case_id": case.case_id,
                    "case_digest": case.digest,
                    "environment_digest": pack.digest,
                    "prompt": case.prompt,
                    "case_payload": _task_payload(case),
                }
                for row, case in zip(rows, selected, strict=True)
            )
        except (
            EnvironmentError,
            KeyError,
            OSError,
            TypeError,
            ValueError,
            VerifiersExportError,
        ):
            return False

    def materialize(self, destination: str | Path) -> Path:
        """Create one new exact-file handoff and verify it before returning."""

        if not self.verify():
            raise VerifiersExportError("refusing to materialize an invalid bundle")
        root = Path(destination)
        if not root.is_absolute():
            raise VerifiersExportError("materialization destination must be absolute")
        root = root.resolve(strict=False)
        if root.exists():
            raise VerifiersExportError(
                "materialization destination must not already exist",
            )
        root.mkdir(parents=True, exist_ok=False)
        for item in self.files:
            relative = _safe_relative_path(item.path)
            path = root.joinpath(*relative.parts)
            path.parent.mkdir(parents=True, exist_ok=True)
            with path.open("xb") as handle:
                handle.write(item.content)
        if not self.verify_materialized(root):
            raise VerifiersExportError("materialized bundle failed self-verification")
        return root

    def verify_materialized(self, root: str | Path) -> bool:
        """Verify exact paths and bytes; symlinks and undeclared files fail closed."""

        try:
            supplied = Path(root)
            if not supplied.is_absolute() or _is_linklike(supplied):
                return False
            materialized = supplied.resolve(strict=True)
            if (
                not materialized.is_dir()
                or _is_linklike(materialized)
                or not self.verify()
            ):
                return False
            observed: dict[str, bytes] = {}
            for path in materialized.rglob("*"):
                if _is_linklike(path):
                    return False
                if path.is_file():
                    relative = path.relative_to(materialized).as_posix()
                    _safe_relative_path(relative)
                    observed[relative] = path.read_bytes()
                elif not path.is_dir():
                    return False
            return observed == self.file_map()
        except (OSError, RuntimeError, ValueError, VerifiersExportError):
            return False


def _task_payload(case: object) -> dict[str, object]:
    # ``case`` stays unannotated to avoid a second public case contract.
    return {
        "case_id": case.case_id,
        "environment_id": case.environment_id,
        "split": case.split,
        "family_id": case.family_id,
        "expected": case.expected,
        "required_citations": list(case.required_citations),
        "required_reason_codes": list(case.required_reason_codes),
        "source_id": case.source_id,
        "evidence_text": case.evidence_text,
        "unordered_fields": list(case.unordered_fields),
    }


def _pyproject(
    package_id: str,
    module_name: str,
    pin: _VerifiersPin,
) -> bytes:
    text = f"""[build-system]
requires = ["setuptools>=83.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "{package_id}"
version = "1.0.0"
description = "Operator-provisioned Lightwork deterministic Verifiers taskset"
requires-python = "~=3.12.0"
dependencies = [
    "verifiers=={pin.version}",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"{module_name}" = ["bundle.lock.json", "tasks.jsonl"]
"""
    return text.encode("utf-8")


def _portable_scorer_source() -> bytes:
    """Return the only scorer source accepted by generated bundles."""

    return _PORTABLE_SCORER_SOURCE.encode("utf-8")


def _taskset_source(
    pin: _VerifiersPin,
    runtime_lock: bytes,
    scorer_source: bytes,
) -> bytes:
    text = (
        _TASKSET_TEMPLATE
        .replace("__VERIFIERS_VERSION__", pin.version)
        .replace("__VERIFIERS_COMMIT__", pin.commit)
        .replace("__RUNTIME_LOCK_SHA256__", _sha256_bytes(runtime_lock))
        .replace("__SCORER_SHA256__", _sha256_bytes(scorer_source))
    )
    return text.encode("utf-8")


def build_verifiers_export_bundle(
    pack: EnvironmentPack,
    *,
    tenant_id: str,
    split: str = "train",
    purpose: BundlePurpose | str = BundlePurpose.TRAINING,
    compatibility: VerifiersCompatibility | str = (
        VerifiersCompatibility.PRIME_RL_V070
    ),
    target: str = "tenant_local",
    hosted_boundary_permission: bool = False,
) -> VerifiersExportBundle:
    """Build an exact-profile package without importing or running Verifiers."""

    tenant = canonical_training_tenant_id(tenant_id)
    destination = normalize_training_target(target).value
    selected_purpose = _normalize_purpose(purpose)
    if selected_purpose is BundlePurpose.TRAINING and split != "train":
        raise VerifiersExportError(
            "training bundles require split='train'; holdout data is eval-only",
        )
    if (
        selected_purpose is BundlePurpose.EVALUATION
        and split not in {"validation", "holdout"}
    ):
        raise VerifiersExportError(
            "evaluation bundles require split='validation' or split='holdout'",
        )
    if selected_purpose is BundlePurpose.TRAINING:
        require_training_readiness(pack)
    profile = _normalize_profile(compatibility)
    pin = _PINS[profile]

    selected = tuple(sorted(pack.split(split), key=lambda item: item.case_id))
    if not selected:
        raise VerifiersExportError(f"environment split {split!r} is empty")

    # This public API remains the answer-disclosure authority. It refuses sealed
    # answers rather than allowing a backend adapter to bypass that control.
    exported = export_rows(pack, split=split, include_answers=True)
    exported_by_id = {str(row["case_id"]): row for row in exported}
    if len(exported_by_id) != len(selected):
        raise VerifiersExportError("backend-neutral export changed the selected case set")

    package_id, module_name = _package_names(
        pack.environment_id,
        tenant,
        selected_purpose,
        split,
        profile,
    )
    task_rows: list[dict[str, object]] = []
    commitments: list[dict[str, str]] = []
    for case in selected:
        row = exported_by_id.get(case.case_id)
        if row is None or row.get("environment_digest") != pack.digest:
            raise VerifiersExportError("case export is not bound to the environment digest")
        prompt = row.get("prompt")
        if (
            not isinstance(prompt, list)
            or len(prompt) != 1
            or not isinstance(prompt[0], dict)
            or set(prompt[0]) != {"role", "content"}
            or prompt[0].get("role") != "user"
            or prompt[0].get("content") != case.prompt
        ):
            raise VerifiersExportError("case export changed the model-visible prompt")
        task_row = {
            "case_id": case.case_id,
            "case_digest": case.digest,
            "environment_digest": pack.digest,
            "prompt": case.prompt,
            "case_payload": _task_payload(case),
        }
        task_rows.append(task_row)
        commitments.append({
            "case_id": case.case_id,
            "case_digest": case.digest,
            "prompt_sha256": case.prompt_digest,
            "row_sha256": _sha256_bytes(_canonical_bytes(task_row)),
        })

    tasks_blob = b"".join(_canonical_bytes(row) + b"\n" for row in task_rows)
    upstream = pin.public_dict()
    upstream_lock = _canonical_bytes({
        "schema": "lightwork.external-training-upstream-lock.v1",
        "verifiers": upstream,
        "prime_rl_compatibility": (
            "v0.7.0" if profile is VerifiersCompatibility.PRIME_RL_V070 else None
        ),
        "auto_install": False,
        "network_required": False,
    })
    scorer_source = _portable_scorer_source()
    scorer_commitment = {
        "path": "scorer.py",
        "sha256": _sha256_bytes(scorer_source),
        "bytes": len(scorer_source),
        "contract": PORTABLE_SCORER_CONTRACT,
    }
    runtime_lock = _canonical_bytes({
        "schema": VERIFIERS_RUNTIME_LOCK_SCHEMA,
        "package_id": package_id,
        "tenant_id": tenant,
        "purpose": selected_purpose.value,
        "environment": {
            "id": pack.environment_id,
            "version": pack.version,
            "digest": pack.digest,
            "split": split,
        },
        "upstream": upstream,
        "tasks": {
            "path": "tasks.jsonl",
            "sha256": _sha256_bytes(tasks_blob),
            "bytes": len(tasks_blob),
        },
        "scorer": scorer_commitment,
        "case_commitments": commitments,
    })
    init_source = (
        b"from .taskset import LightworkTaskset\n\n"
        b'__all__ = ["LightworkTaskset"]\n'
    )
    payload_files = tuple(sorted((
        VerifiersBundleFile("UPSTREAM.lock.json", upstream_lock),
        VerifiersBundleFile("pyproject.toml", _pyproject(package_id, module_name, pin)),
        VerifiersBundleFile(f"src/{module_name}/__init__.py", init_source),
        VerifiersBundleFile(
            f"src/{module_name}/bundle.lock.json",
            runtime_lock,
        ),
        VerifiersBundleFile(
            f"src/{module_name}/scorer.py",
            scorer_source,
        ),
        VerifiersBundleFile(
            f"src/{module_name}/taskset.py",
            _taskset_source(pin, runtime_lock, scorer_source),
        ),
        VerifiersBundleFile(f"src/{module_name}/tasks.jsonl", tasks_blob),
    ), key=lambda item: item.path))
    file_commitments = {
        item.path: {"sha256": item.sha256, "bytes": len(item.content)}
        for item in payload_files
    }
    descriptor = {
        "schema": VERIFIERS_EXPORT_SCHEMA,
        "package_id": package_id,
        "module_name": module_name,
        "tenant_id": tenant,
        "purpose": selected_purpose.value,
        "environment": {
            "id": pack.environment_id,
            "version": pack.version,
            "digest": pack.digest,
            "split": split,
        },
        "boundary": {
            "target": destination,
            "hosted_permission": hosted_boundary_permission,
            "cross_tenant": False,
        },
        "upstream": upstream,
        "files": file_commitments,
    }
    bundle_digest = _sha256_bytes(_canonical_bytes(descriptor))
    decision = admit_training_boundary(
        pack,
        tenant_id=tenant,
        target=destination,
        bundle_digest=bundle_digest,
        hosted_boundary_permission=hosted_boundary_permission,
    )
    admission_digest = training_admission_digest(
        decision,
        tenant_id=tenant,
        bundle_digest=bundle_digest,
    )
    manifest = {
        "schema": VERIFIERS_EXPORT_SCHEMA,
        "bundle_digest": bundle_digest,
        "descriptor": descriptor,
        "package_id": package_id,
        "module_name": module_name,
        "tenant_id": tenant,
        "environment": {
            "id": pack.environment_id,
            "version": pack.version,
            "digest": pack.digest,
            "case_schema": CASE_SCHEMA,
            "purpose": selected_purpose.value,
            "split": split,
            "case_commitments": commitments,
        },
        "boundary": descriptor["boundary"],
        "admission": {
            "digest": admission_digest,
            "decision_digest": decision.digest,
            "decision": decision.public_dict(),
        },
        "upstream": upstream,
        "controls": {
            "execution_performed": False,
            "auto_install": False,
            "network_required": False,
            "upload_enabled": False,
            "telemetry_enabled": False,
            "model_visible_fields": ["prompt"],
            "ambient_lightwork_dependency": False,
            "trusted_scoring_function": f"{module_name}.scorer.score_output",
            "trusted_scoring_source_sha256": scorer_commitment["sha256"],
            "runtime_scorer_integrity_check": True,
            "runtime_task_integrity_check": True,
        },
        "files": file_commitments,
    }
    manifest_blob = _canonical_bytes(manifest)
    files = tuple(sorted(
        (*payload_files, VerifiersBundleFile("manifest.json", manifest_blob)),
        key=lambda item: item.path,
    ))
    bundle = VerifiersExportBundle(
        package_id=package_id,
        module_name=module_name,
        tenant_id=tenant,
        target=decision.target,
        hosted_boundary_permission=hosted_boundary_permission,
        environment_id=pack.environment_id,
        environment_version=pack.version,
        environment_digest=pack.digest,
        purpose=selected_purpose.value,
        split=split,
        compatibility=profile.value,
        verifiers_version=pin.version,
        verifiers_tag=pin.tag,
        verifiers_revision=pin.commit,
        case_ids=tuple(case.case_id for case in selected),
        files=files,
        digest=bundle_digest,
        boundary_decision_digest=decision.digest,
        admission_digest=admission_digest,
        manifest_sha256=_sha256_bytes(manifest_blob),
    )
    if not bundle.verify():
        raise VerifiersExportError("generated bundle failed internal verification")
    return bundle


__all__ = [
    "BundlePurpose",
    "PORTABLE_SCORER_CONTRACT",
    "STANDALONE_VERIFIERS_COMMIT",
    "STANDALONE_VERIFIERS_SOURCE",
    "STANDALONE_VERIFIERS_TAG",
    "STANDALONE_VERIFIERS_VERSION",
    "VERIFIERS_COMMIT",
    "VERIFIERS_EXPORT_SCHEMA",
    "VERIFIERS_REPOSITORY",
    "VERIFIERS_RUNTIME_LOCK_SCHEMA",
    "VERIFIERS_SOURCE",
    "VERIFIERS_TAG",
    "VERIFIERS_VERSION",
    "VerifiersBundleFile",
    "VerifiersCompatibility",
    "VerifiersExportBundle",
    "VerifiersExportError",
    "build_verifiers_export_bundle",
]
