"""eBPF syscall monitor for agent process trees (roadmap: 2027 H2 Safety).

An OPERATOR-run supervisor around ``bpftrace``: it generates a bpftrace
program that follows a PID tree (seed PID plus every descendant forked while
attached) and traces ``execve`` / ``connect`` / ``openat`` plus a configurable
watchlist of suspicious syscalls, parses the program's line output into
structured :class:`SyscallEvent` records, and raises alerts on watchlist hits
through an injected callback.

Honest scope: the program generator, the supervisor loop, and the parser are
fully deterministic and offline-testable (the runner is an injected seam). The
LIVE attach is the only privileged part -- it needs root and a ``bpftrace``
binary at runtime, and the default runner refuses politely when either is
missing. Tests never invoke the default runner.

Default OFF: the live ``run`` entry point requires ``[ebpf_monitor] enable =
true`` in ``~/.maverick/config.toml`` on top of the operator explicitly
invoking it. Generating/printing the program is always allowed (it is inert
text).

CLI::

    python -m maverick.ebpf_monitor program --pid 1234        # print the program
    sudo python -m maverick.ebpf_monitor run --pid 1234       # live attach (root + bpftrace)
"""
from __future__ import annotations

import argparse
import logging
import re
import shutil
import sys
from collections.abc import Callable, Iterable
from dataclasses import dataclass

log = logging.getLogger(__name__)

# Syscall names become tracepoint identifiers inside the generated program;
# anything else is rejected so a config value can't inject bpftrace code.
_SYSCALL_RE = re.compile(r"^[a-z0-9_]{1,32}$")

# Always traced (the visibility baseline): process execution, network
# connection attempts, file opens.
BASE_SYSCALLS = ("execve", "connect", "openat")

# Default suspicious-syscall watchlist: privilege / kernel / introspection
# operations an agent's tool subprocess has no business making.
DEFAULT_WATCHLIST = (
    "ptrace",
    "setuid",
    "setns",
    "mount",
    "init_module",
    "finit_module",
    "kexec_load",
    "memfd_create",
)

# Line protocol emitted by the generated program: PREFIX|syscall|pid|comm|detail
_PREFIX = "MAVEBPF"

# Syscalls whose first tracepoint arg is a filename worth printing.
_PATH_ARG = {"execve": "filename", "openat": "filename"}

Runner = Callable[[str], Iterable[str]]
AlertFn = Callable[["SyscallEvent"], None]


class BpftraceUnavailable(RuntimeError):
    """Live attach refused: bpftrace and/or root privileges are missing."""


def enabled() -> bool:
    """``[ebpf_monitor] enable`` -- default OFF."""
    try:
        from .config import load_config

        cfg = (load_config() or {}).get("ebpf_monitor") or {}
        return bool(cfg.get("enable", False))
    except Exception:  # noqa: BLE001 -- config reads fail open (to OFF)
        return False


def _validated_watchlist(watchlist: Iterable[str]) -> tuple[str, ...]:
    out: list[str] = []
    for name in watchlist:
        if not isinstance(name, str) or not _SYSCALL_RE.fullmatch(name):
            raise ValueError(f"invalid syscall name in watchlist: {name!r}")
        if name not in out:
            out.append(name)
    return tuple(out)


def generate_program(pid: int, *, watchlist: Iterable[str] = DEFAULT_WATCHLIST) -> str:
    """Render the bpftrace program for one PID tree.

    The program seeds ``@tracked`` with ``pid``, adds children on
    ``sched_process_fork`` (so the whole tool/sandbox subtree stays covered),
    drops exited PIDs, and prints one ``MAVEBPF|...`` line per traced syscall.
    Pure text generation -- nothing is executed here.
    """
    if not isinstance(pid, int) or isinstance(pid, bool) or pid <= 0:
        raise ValueError(f"pid must be a positive integer, got {pid!r}")
    watch = _validated_watchlist(watchlist)
    syscalls = list(BASE_SYSCALLS) + [s for s in watch if s not in BASE_SYSCALLS]

    blocks = [
        "// Generated by maverick.ebpf_monitor -- PID-tree syscall monitor.",
        f"// Seed PID: {pid}; run under root with: bpftrace -e '<this program>'",
        "BEGIN {",
        f"  @tracked[{pid}] = 1;",
        "}",
        "tracepoint:sched:sched_process_fork {",
        "  if (@tracked[args->parent_pid] == 1) {",
        "    @tracked[args->child_pid] = 1;",
        "  }",
        "}",
        "tracepoint:sched:sched_process_exit /@tracked[pid]/ {",
        "  delete(@tracked[pid]);",
        "}",
    ]
    for name in syscalls:
        arg = _PATH_ARG.get(name)
        detail = f"str(args->{arg})" if arg else '""'
        blocks += [
            f"tracepoint:syscalls:sys_enter_{name} /@tracked[pid]/ {{",
            f'  printf("{_PREFIX}|{name}|%d|%s|%s\\n", pid, comm, {detail});',
            "}",
        ]
    return "\n".join(blocks) + "\n"


@dataclass(frozen=True)
class SyscallEvent:
    """One parsed monitor line."""
    syscall: str
    pid: int
    comm: str
    detail: str
    suspicious: bool


def parse_line(
    line: str, *, watchlist: Iterable[str] = DEFAULT_WATCHLIST
) -> SyscallEvent | None:
    """Parse one bpftrace output line into a :class:`SyscallEvent`.

    Returns None for anything that is not a well-formed ``MAVEBPF`` record
    (bpftrace banners, attach notices, torn lines) -- the supervisor skips
    those rather than guessing.
    """
    if not isinstance(line, str):
        return None
    parts = line.strip().split("|", 4)
    if len(parts) != 5 or parts[0] != _PREFIX:
        return None
    _, syscall, pid_s, comm, detail = parts
    if not _SYSCALL_RE.fullmatch(syscall):
        return None
    try:
        pid = int(pid_s)
    except ValueError:
        return None
    if pid <= 0:
        return None
    return SyscallEvent(
        syscall=syscall, pid=pid, comm=comm, detail=detail,
        suspicious=syscall in set(watchlist),
    )


def _default_runner(program: str) -> Iterable[str]:
    """LIVE attach: run ``bpftrace -e <program>`` and yield its stdout lines.

    Needs root and an installed ``bpftrace``; refuses politely (with install
    guidance) when either is missing. Never used by tests -- they inject a
    fake runner. This is an operator-launched supervisor process, not an
    agent tool, so it does not route through ``sandbox.exec()``.
    """
    import os
    import subprocess

    if shutil.which("bpftrace") is None:
        raise BpftraceUnavailable(
            "bpftrace is not installed; install it (e.g. 'apt install bpftrace') "
            "to use the live eBPF monitor."
        )
    if getattr(os, "geteuid", lambda: 0)() != 0:
        raise BpftraceUnavailable(
            "the live eBPF monitor needs root to attach tracepoints; "
            "re-run under sudo."
        )
    proc = subprocess.Popen(  # operator-run supervisor; see docstring
        ["bpftrace", "-e", program],
        stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, text=True,
    )
    try:
        assert proc.stdout is not None
        yield from proc.stdout
    finally:
        proc.terminate()
        try:
            proc.wait(timeout=5)
        except Exception:  # noqa: BLE001 -- best-effort teardown
            proc.kill()


class EbpfMonitor:
    """Supervise one PID tree: generate the program, feed its output through
    the parser, collect events, and alert on watchlist hits.

    ``runner`` and ``alert`` are the injected seams; the default runner is the
    live bpftrace attach. The monitor stops when the runner's line stream ends
    (or ``max_events`` is reached), so a fake runner fully controls a test.
    """

    def __init__(
        self,
        pid: int,
        *,
        watchlist: Iterable[str] = DEFAULT_WATCHLIST,
        runner: Runner | None = None,
        alert: AlertFn | None = None,
    ):
        self.pid = pid
        self.watchlist = _validated_watchlist(watchlist)
        self.program = generate_program(pid, watchlist=self.watchlist)
        self._runner = runner or _default_runner
        self._alert = alert
        self.events: list[SyscallEvent] = []
        self.alerts: list[SyscallEvent] = []

    def run(self, *, max_events: int | None = None) -> list[SyscallEvent]:
        """Consume the runner's output until it ends. Returns all events."""
        for line in self._runner(self.program):
            event = parse_line(line, watchlist=self.watchlist)
            if event is None:
                continue
            self.events.append(event)
            if event.suspicious:
                self.alerts.append(event)
                if self._alert is not None:
                    try:
                        self._alert(event)
                    except Exception:  # noqa: BLE001 -- a broken alert sink
                        log.warning(   # must not stop the monitor
                            "ebpf monitor: alert callback failed for %s", event.syscall,
                        )
            if max_events is not None and len(self.events) >= max_events:
                break
        return self.events


def _log_alert(event: SyscallEvent) -> None:
    log.warning(
        "ebpf monitor ALERT: watchlist syscall %s by pid=%d comm=%s detail=%s",
        event.syscall, event.pid, event.comm, event.detail,
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python -m maverick.ebpf_monitor",
        description="eBPF (bpftrace) syscall monitor for an agent PID tree.",
    )
    sub = parser.add_subparsers(dest="cmd", required=True)
    for name, help_ in (
        ("program", "print the generated bpftrace program (inert text)"),
        ("run", "live-attach bpftrace to the PID tree (root + bpftrace required)"),
    ):
        p = sub.add_parser(name, help=help_)
        p.add_argument("--pid", type=int, required=True, help="root PID of the tree to monitor")
        p.add_argument(
            "--watch", default=",".join(DEFAULT_WATCHLIST),
            help="comma-separated suspicious-syscall watchlist",
        )
    args = parser.parse_args(argv)

    watchlist = tuple(s.strip() for s in args.watch.split(",") if s.strip())
    try:
        if args.cmd == "program":
            print(generate_program(args.pid, watchlist=watchlist), end="")
            return 0
        if not enabled():
            print(
                "refused: the eBPF monitor is off by default. Set "
                "[ebpf_monitor] enable = true in ~/.maverick/config.toml to allow "
                "live attach.",
                file=sys.stderr,
            )
            return 2
        monitor = EbpfMonitor(args.pid, watchlist=watchlist, alert=_log_alert)
        events = monitor.run()
    except (ValueError, BpftraceUnavailable) as e:
        print(f"ebpf monitor failed: {e}", file=sys.stderr)
        return 2
    print(f"monitor stopped: {len(events)} event(s), {len(monitor.alerts)} alert(s)")
    return 0


if __name__ == "__main__":  # pragma: no cover -- exercised via main() in tests
    raise SystemExit(main())


__all__ = [
    "BASE_SYSCALLS",
    "DEFAULT_WATCHLIST",
    "BpftraceUnavailable",
    "EbpfMonitor",
    "SyscallEvent",
    "enabled",
    "generate_program",
    "parse_line",
    "main",
]
