"""HTML-to-app scaffolder: turn a static HTML mockup into a starter project.

Parses an HTML page (stdlib ``html.parser`` — no external dep) into a structural
plan — title, headings, forms with their fields, links, and asset counts — then
scaffolds a minimal runnable project (``index.html`` + an ``app.js`` stub wired to
the discovered forms + a ``README.md`` describing the components). Useful for
bootstrapping an app from a designer's mockup. ``analyze_html`` is the pure,
unit-tested core; the ``html_to_app`` tool writes the scaffold (path-confined to
the destination dir).
"""
from __future__ import annotations

from html.parser import HTMLParser
from pathlib import Path


class _Analyzer(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.title = ""
        self.headings: list[str] = []
        self.forms: list[dict] = []
        self.links: list[str] = []
        self.images = 0
        self.scripts = 0
        self._in_title = False
        self._in_heading = ""
        self._cur_form: dict | None = None

    def handle_starttag(self, tag, attrs):
        a = dict(attrs)
        if tag == "title":
            self._in_title = True
        elif tag in ("h1", "h2", "h3", "h4", "h5", "h6"):
            self._in_heading = tag
        elif tag == "form":
            self._cur_form = {
                "action": a.get("action", ""),
                "method": (a.get("method", "get") or "get").lower(),
                "fields": [],
            }
        elif tag in ("input", "select", "textarea"):
            field = {"name": a.get("name", ""), "type": a.get("type", tag),
                     "required": "required" in a}
            if self._cur_form is not None:
                self._cur_form["fields"].append(field)
        elif tag == "a" and a.get("href"):
            self.links.append(a["href"])
        elif tag == "img":
            self.images += 1
        elif tag == "script":
            self.scripts += 1

    def handle_endtag(self, tag):
        if tag == "title":
            self._in_title = False
        elif tag == self._in_heading:
            self._in_heading = ""
        elif tag == "form" and self._cur_form is not None:
            self.forms.append(self._cur_form)
            self._cur_form = None

    def handle_data(self, data):
        s = data.strip()
        if not s:
            return
        if self._in_title:
            self.title = (self.title + " " + s).strip()
        elif self._in_heading:
            self.headings.append(s)


def analyze_html(html: str) -> dict:
    """Return a structural plan of the HTML (title/headings/forms/links/assets)."""
    p = _Analyzer()
    try:
        p.feed(html or "")
        if p._cur_form is not None:  # unterminated <form>
            p.forms.append(p._cur_form)
    except Exception:  # pragma: no cover -- malformed HTML must not raise
        pass
    return {
        "title": p.title or "Untitled App",
        "headings": p.headings,
        "forms": p.forms,
        "links": p.links,
        "images": p.images,
        "scripts": p.scripts,
    }


def _app_js(plan: dict) -> str:
    lines = [
        "// Generated by Maverick html_to_app scaffolder.",
        "document.addEventListener('DOMContentLoaded', () => {",
    ]
    if plan["forms"]:
        lines.append("  document.querySelectorAll('form').forEach((form, i) => {")
        lines.append("    form.addEventListener('submit', (e) => {")
        lines.append("      e.preventDefault();")
        lines.append("      const data = Object.fromEntries(new FormData(form));")
        lines.append("      console.log(`form ${i} submitted`, data);")
        lines.append("      // TODO: POST `data` to your backend, then remove the alert below.")
        lines.append("      // Until wired, fail VISIBLY rather than silently dropping the submission:")
        lines.append("      alert('This form is not connected to a backend yet — your submission was NOT sent (generated scaffold).');")
        lines.append("    });")
        lines.append("  });")
    else:
        lines.append("  console.log('app ready');")
    lines.append("});")
    return "\n".join(lines) + "\n"


def _readme(plan: dict) -> str:
    out = [f"# {plan['title']}", "", "Scaffolded by Maverick from an HTML mockup.",
           "", "## Components"]
    out.append(f"- Headings: {len(plan['headings'])}")
    out.append(f"- Forms: {len(plan['forms'])}")
    for i, f in enumerate(plan["forms"]):
        names = ", ".join(fld["name"] or "(unnamed)" for fld in f["fields"]) or "(none)"
        out.append(f"  - form {i}: {f['method'].upper()} {f['action'] or '(no action)'} "
                   f"— fields: {names}")
    out.append(f"- Links: {len(plan['links'])}")
    out.append(f"- Images: {plan['images']}")
    out.append("")
    out.append("## Run")
    out.append("Open `index.html` in a browser (or serve with `python -m http.server`).")
    return "\n".join(out) + "\n"


def scaffold(html: str, dest: Path) -> dict:
    """Write index.html + app.js + README.md into ``dest``; return the plan."""
    dest = Path(dest)
    dest.mkdir(parents=True, exist_ok=True)
    plan = analyze_html(html)
    # Inject the app.js include if the source didn't reference one.
    page = html or ""
    if "app.js" not in page:
        if "</body>" in page:
            page = page.replace("</body>", '  <script src="app.js"></script>\n</body>')
        else:
            page = page + '\n<script src="app.js"></script>\n'
    (dest / "index.html").write_text(page, encoding="utf-8")
    (dest / "app.js").write_text(_app_js(plan), encoding="utf-8")
    (dest / "README.md").write_text(_readme(plan), encoding="utf-8")
    plan["written"] = ["index.html", "app.js", "README.md"]
    return plan


_SCHEMA = {
    "type": "object",
    "properties": {
        "op": {"type": "string", "enum": ["analyze", "scaffold"]},
        "html": {"type": "string", "description": "HTML source"},
        "dest": {"type": "string", "description": "output directory (scaffold op)"},
    },
    "required": ["op", "html"],
}


def _run(args: dict, sandbox=None) -> str:
    import json as _json
    op = args.get("op")
    html = args.get("html")
    if not html:
        return "ERROR: html is required"
    if op == "analyze":
        return _json.dumps(analyze_html(html), indent=2)
    if op == "scaffold":
        dest = args.get("dest")
        if not dest:
            return "ERROR: scaffold requires dest"
        # Confine the scaffold destination to the sandbox workspace: an
        # unconfined `dest` is an arbitrary-directory write of model-controlled
        # index.html/app.js (docroot/dotfile clobber, stored XSS).
        from .tools.ffmpeg_tool import _safe_path
        try:
            safe_dest = Path(_safe_path(sandbox, dest))
            plan = scaffold(html, safe_dest)
        except ValueError as e:
            return f"ERROR: {e}"
        except OSError as e:
            return f"ERROR: {e}"
        return (f"scaffolded '{plan['title']}' into {safe_dest}: "
                f"{', '.join(plan['written'])} "
                f"({len(plan['forms'])} form(s), {len(plan['links'])} link(s))")
    return f"ERROR: unknown op {op!r}"


def html_to_app(sandbox=None):
    from .tools import Tool
    return Tool(
        name="html_to_app",
        description=(
            "Turn a static HTML mockup into a starter project. ops: analyze "
            "(html) -> structural plan (title/headings/forms/links/assets), "
            "scaffold (html, dest) -> writes index.html + app.js stub + README. "
            "The destination is confined to the workspace."
        ),
        input_schema=_SCHEMA,
        fn=lambda args: _run(args, sandbox),
    )


__all__ = ["analyze_html", "scaffold", "html_to_app"]
