# Homebrew formula for Lightwork (source of truth lives in the monorepo).
#
# To make it installable, this file is mirrored into a Homebrew *tap* repo
# named `homebrew-tap` under the project organization. That tap is not deployed
# yet; once it exists and this formula is synced, the intended command is:
#
#     brew install Daybreak-AI-Labs/tap/maverick
#
# The .github/workflows/homebrew-bump.yml action keeps the `url`/`sha256`
# current: on each `v*` release it resolves the published sdist from PyPI,
# generates hash-locked dependency requirements, and opens a PR updating this
# file (and you sync it to the tap repo).
#
# It installs the checksum-verified `maverick-agent` source plus the installer
# wizard dependencies into an isolated virtualenv, then links the `maverick` CLI
# onto the PATH.
class Maverick < Formula
  include Language::Python::Virtualenv

  desc "AI agent swarm that runs locally, works for hours, under a budget cap"
  homepage "https://github.com/Daybreak-AI-Labs/Lightwork"
  url "https://files.pythonhosted.org/packages/source/m/maverick-agent/maverick_agent-0.1.6.tar.gz"
  sha256 "0000000000000000000000000000000000000000000000000000000000000000" # set by homebrew-bump.yml
  license :cannot_represent

  depends_on "python@3.12"

  def install
    python = Formula["python@3.12"].opt_bin/"python3.12"
    virtualenv_create(libexec, python)

    sections = File.read(__FILE__).split(/^__END__\n/, 2)
    odie "generated requirement payload is missing" unless sections.length == 2
    payload = sections[1]
    build_match = payload.match(
      /^# LIGHTWORK_BUILD_REQUIREMENTS_BEGIN\n(.*?)^# LIGHTWORK_BUILD_REQUIREMENTS_END$/m,
    )
    runtime_match = payload.match(
      /^# LIGHTWORK_RUNTIME_REQUIREMENTS_BEGIN\n(.*?)^# LIGHTWORK_RUNTIME_REQUIREMENTS_END$/m,
    )
    odie "generated build requirements are missing" if build_match.nil?
    odie "generated runtime requirements are missing" if runtime_match.nil?
    build_lock = build_match[1]
    runtime_lock = runtime_match[1]

    # Python 3.12 virtualenvs no longer include pip/setuptools. Homebrew creates
    # this venv with --without-pip, so use the brewed interpreter's pip with its
    # supported --python target and provision the exact hashed build backend.
    build_requirements = libexec/"build-requirements.txt"
    build_requirements.write(build_lock)
    system python, "-m", "pip", "--python=#{libexec}/bin/python", "install",
           "--require-hashes", "--only-binary=:all:", "--no-deps",
           "-r", build_requirements

    # Install the Homebrew-downloaded, checksum-verified sdist before its
    # runtime cohort. The generated runtime lock omits maverick-agent itself,
    # so no public lookalike can replace these source bytes.
    system python, "-m", "pip", "--python=#{libexec}/bin/python", "install",
           "--no-deps", "--no-build-isolation", buildpath

    runtime_requirements = libexec/"runtime-requirements.txt"
    runtime_requirements.write(runtime_lock)
    system python, "-m", "pip", "--python=#{libexec}/bin/python", "install",
           "--require-hashes", "--only-binary=:all:", "--no-deps",
           "-r", runtime_requirements
    system python, "-m", "pip", "--python=#{libexec}/bin/python", "check"
    bin.install_symlink Dir[libexec/"bin/maverick"]
  end

  test do
    # `maverick version` prints the installed package versions; assert this
    # formula's version shows up, proving the CLI installed and runs.
    assert_match version.to_s, shell_output("#{bin}/maverick version")
  end
end

__END__
# Hash-locked build/runtime requirements are generated by homebrew-bump.yml.
# The initial placeholder formula is intentionally not installable until the
# first release bump writes the exact transitive dependency set and hashes.
# LIGHTWORK_BUILD_REQUIREMENTS_BEGIN
# generated by homebrew-bump.yml
# LIGHTWORK_BUILD_REQUIREMENTS_END
# LIGHTWORK_RUNTIME_REQUIREMENTS_BEGIN
# generated by homebrew-bump.yml
# LIGHTWORK_RUNTIME_REQUIREMENTS_END
